version: '3'

services:
 db:
   container_name: db_dev_blog
   image: postgres:10-alpine
   networks:
     - main
   volumes:
     - pg-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=blog
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecretpassword

 backend:
   container_name: backend_dev_blog
   build: ./backend
   command: "sh -c /start_dev.sh"
   user: root
   volumes:
     - ./backend:/backend
     - django-static:/backend/static
   ports:
     - "8000:8000"
   networks:
     - main
   environment:
     - DB_HOST=db
     - DB_NAME=blog
     - DB_USER=postgres
     - DB_PASS=supersecretpassword
   depends_on:
     - db

 nginx:
   container_name: nginx_dev_blog
   build:
     context: .
     dockerfile: nginx/Dockerfile
   depends_on:
     - backend
   ports:
     - "80:80"
   volumes:
     - ./nginx/default.conf:/etc/nginx/nginx.conf
   networks:
     - main

 redis:
   image: redis:alpine
   container_name: redis_dev_blog
   networks:
     - main

 celery:
    build: ./backend
    container_name: celery_dev_blog
    command: sh -c 'celery -A blog.celery  worker -l info'
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    networks:
      - main


volumes:
  django-static:
  pg-data:

networks:
  main:
    driver: bridge
