version: '3'

services:
 db:
   container_name: db_dev_blog
   image: postgres:10-alpine
   networks:
     - main
   environment:
     - POSTGRES_DB=blog
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecretpassword

 backend:
   container_name: backend_dev_blog
   build: ./backend
   command: "sh -c /start_dev.sh"
   volumes:
     - ./backend:/backend
   ports:
     - "8000:8000"
   networks:
     - main
   environment:
     - DB_HOST=db
     - DB_NAME=blog
     - DB_USER=postgres
     - DB_PASS=supersecretpassword
   depends_on:
     - db

 frontend:
  container_name: frontend_dev_blog
  build: ./frontend
  command: "npm start"
  volumes:
    - ./frontend:/frontend/
  ports:
    - "4200:4200"
  networks:
    - main
  depends_on:
    - backend
    - db


networks:
  main:
    driver: bridge
